version: 1.0.{build}
image:
  - Ubuntu1604
  - Ubuntu1804
  # - Visual Studio 2017
stack: python 3
clone_depth: 30

environment:
  CTEST_OUTPUT_ON_FAILURE: ON
platform:
  - x64

# Need to add ssh_keys for submodules to work on windows
# howto article: https://www.appveyor.com/docs/how-to/private-git-sub-modules/
for:
-
  matrix:
    only:
      - image: Ubuntu1604
       - install:
          - sh: sudo -E apt-add-repository ppa:ubuntu-toolchain-r/test -y
          - sh: sudo apt-get -yq update > /dev/null
          - sh: sudo apt-get -yq install gcc-8 gfortran-8 > /dev/null
          - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-8
          - sh: sudo update-alternatives --auto gcc
          - sh: sudo update-alternatives --display gcc
          - sh: export FC=gfortran
          - sh: export CC=gcc
          - sh: $FC --version
          - sh: $CC --version
          - sh: cmake --version

      - image: Ubuntu1804
      install:
          - sh: sudo -E apt-add-repository ppa:ubuntu-toolchain-r/test -y
          - sh: export FC=gfortran
          - sh: export CC=gcc
          - sh: $FC --version
          - sh: $CC --version
          - sh: cmake --version

build: off
build_script:
  - ps: mkdir build
  - cmd: echo N Q|cmd /k gen-VisualStudio-solution.bat # This will currently fail
  - ps: cd build
  - sh: cmake ..
  - sh: cmake --build .
#  - ps: cmake --build . # Need to figure out Intel Compilers on appveyor first

test_script:
  - sh: ctest
  - cmd: ctest

notifications:
- provider: Email
  to:
  - ianeporter88@gmail.com
  subject: '{{#passed}} Build {{projectName}} {{buildVersion}} passed {{/passed}} {{#failed}} Build {{projectName}} {{buildVersion}} failed {{/failed}}'
  message: >-
    <div style="font-family:'Segoe UI',Arial,Sans-Serif;font-size:10pt;">
        {{#passed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#1DC420;"><a href="{{buildUrl}}" style="color:#078DC7;">Build {{projectName}} {{buildVersion}} passed</a></h1>{{/passed}}
        {{#failed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#ff3228;"><a href="{{buildUrl}}" style="color:#ff3228;">Build {{projectName}} {{buildVersion}} failed</a></h1>{{/failed}}
        <p style="color: #888;">
            Commit <a href="{{commitUrl}}">{{commitId}}</a> by <a href="mailto:{{commitAuthorEmail}}">{{commitAuthor}}</a> on {{commitDate}}:
            <br />
            <span style="font-size: 110%;color:#222;">{{commitMessage}}</span>
        </p>
        <p><a href="{{notificationSettingsUrl}}" style="font-size:85%;color:#999;">Configure your notification preferences</a></p>
    </div>
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  subject: '{{#passed}} Build {{projectName}} {{buildVersion}} passed {{/passed}} {{#failed}} Build {{projectName}} {{buildVersion}} failed {{/failed}}'
  message: >-
    <div style="font-family:'Segoe UI',Arial,Sans-Serif;font-size:10pt;">
        {{#passed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#1DC420;"><a href="{{buildUrl}}" style="color:#078DC7;">Build {{projectName}} {{buildVersion}} passed</a></h1>{{/passed}}
        {{#failed}}
        <h1 style="font-size: 150%;font-weight:normal; color:#ff3228;"><a href="{{buildUrl}}" style="color:#ff3228;">Build {{projectName}} {{buildVersion}} failed</a></h1>{{/failed}}
        <p style="color: #888;">
            Commit <a href="{{commitUrl}}">{{commitId}}</a> by <a href="mailto:{{commitAuthorEmail}}">{{commitAuthor}}</a> on {{commitDate}}:
            <br />
            <span style="font-size: 110%;color:#222;">{{commitMessage}}</span>
        </p>
        <p><a href="{{notificationSettingsUrl}}" style="font-size:85%;color:#999;">Configure your notification preferences</a></p>
    </div>
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
